import Head from 'next/head'

import styles from '../styles/Home.module.css'
import {signIn,signOut,useSession} from 'next-auth/client'

export default function Home() {

  const {session,loadingSession} = useSession();

  //loading time
  if (loadingSession) {
    return <p>Loading...</p>
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* no current session */}
      {
        !session && (
          <>
            <button onClick={()=> signIn()}>Sign In</button>
          </>
        )
      }


      {/* currently there is a session */}
      {
        session && (
          <>
            <h4>You r logged in as : {session.user.name}</h4>
            <div className={styles.boxCenter}>
              <h4>Email : {session.user.email}</h4>
              <br />
              {session.user.image && (
                <span>
                  <img src={session.user.image} alt={session.user.name}/>
                </span>
              )}

            </div>
            <br/>
            <br/>
            <button className={styles.primaryButton} onClick={()=> signOut()}>
              Sign out
            </button>
          </>
        )
      }

      
    </div>
  )
}
